# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-16 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=200)),
                ('course_medium', models.CharField(max_length=10)),
                ('course_number', models.IntegerField()),
                ('course_description', models.TextField()),
            ],
        ),
    ]
