# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-16 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_auto_20161016_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='question_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_statement', models.TextField()),
                ('option1', models.CharField(max_length=100)),
                ('option2', models.CharField(max_length=100)),
                ('option3', models.CharField(max_length=100)),
                ('option4', models.CharField(max_length=100)),
                ('answer', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_title', models.CharField(max_length=250)),
                ('unit_number', models.IntegerField()),
                ('unit_description', models.CharField(max_length=250)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Subject')),
            ],
        ),
        migrations.AddField(
            model_name='question_detail',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Unit'),
        ),
    ]
