# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-16 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_auto_20161016_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_detail',
            name='importance_level',
            field=models.CharField(choices=[('easy', 'Easy'), ('Diff', 'Difficult')], default='easy', max_length=4),
        ),
    ]
